### ISSUE TITLE
React library creation failing

### ISSUE THREAD

**Issue by hirensavalias** [Silind-Software/direflow#215]
**Describe the bug**  
I just created a direflow sample project with direflow-cli and when im trying npm run build:lib, im getting below error message:

**More Details**
Windows 10
Javascript
Npm
direflow-cli sample project version
```
"name": "direflow-sample-project",
"description": "This project is created using Direflow",
"version": "1.0.0",
```

**To reproduce**  
1. `npm i -g direflow-cli`
2. `direflow create`
3. `cd <project-folder>`
4. ` npm install`
5. `npm run build` - works fine
6. `npm run build:lib`
7. throws error

`C:\developer\direflow-sample-project>npm run build:lib
> direflow-sample-project@1.0.0 build:lib
> direflow-scripts build:lib
Building React component library...
events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: spawn webpack ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn webpack',
  path: 'webpack',
  spawnargs: [
    '--config',
    'C:\\developer\\direflow-sample-project\\node_modules\\direflow-scripts\\webpack.config.js'
  ]
}`

**Comment by cedric-sd** [comment]
I have same problem, and i cant resolve this, if you resolve could post here pls

**Comment by luchobertello** [comment]
Same issue here. Direflow v3.5.5
Windows 10 Enterprise 64bit

**Comment by dalopezarco** [comment]
Try to run it with Windows WSL Ubuntu and it should work

**Comment by kidqn** [comment]
anyone fix it? I got the same issue on Windows, cannot build lib, only build successful
