### ISSUE TITLE
direflow-create  doesn't work

### ISSUE THREAD

**Issue by mayank893arora** [Silind-Software/direflow#300]
**Describe the bug**  
I am getting below error while running command direflow-create 

Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/local/lib/node_modules/direflow-cli/node_modules/boxen/index.js not supported.
Instead change the require of index.js in null to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/usr/local/lib/node_modules/direflow-cli/dist/messages.js:8:31)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/usr/local/lib/node_modules/direflow-cli/dist/create.js:50:18)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/usr/local/lib/node_modules/direflow-cli/dist/cli.js:45:16)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/usr/local/lib/node_modules/direflow-cli/bin/direflow:4:13) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.5.1

**To reproduce**  
1. Install '...'
2. Open '....'
3. Build '....'

**Expected behavior**  

**Package Manager:**  
To install Direflow, I used... (npm / yarn / something else)

**Screenshots**  
<img width="747" alt="Screenshot 2023-08-25 at 3 16 49 AM" src="https://github.com/Silind-Software/direflow/assets/13931407/c0314ea2-ce42-4c35-8466-7de38b8b1261">

**Additional context**

**Comment by qhansen628** [comment]
I'm having the exact same issue

**Comment by amanvlink** [comment]
I'm encountering the same error when trying to use the **direflow create** command.

**Comment by MJT-Arthas** [comment]
I'm encountering the same error when trying to use the direflow create command.

**Comment by dmarcucci** [comment]
Same problem here.

**Comment by MJT-Arthas** [comment]
这是来自邮箱的自动回复邮件。您好！邮件我已收到，我会尽快处理的！祝您工作顺利，生活愉快！上海大学 马锦涛
