### ISSUE TITLE
Error when use `async`

### ISSUE THREAD

**Issue by lucasinocente** [Silind-Software/direflow#65]
**Describe the bug**  
If I need use `async` in the component function, return error.

**To reproduce**  
1. `direflow create`
2. At line 6 add async:

```
import React, { useContext } from 'react';
import PropTypes from 'prop-types';
import { EventContext, Styled } from 'direflow-component';
import styles from './App.css';

const App = async (props) => {
  const dispatch = useContext(EventContext);

  const handleClick = () => {
    const event = new Event('my-event');
    dispatch(event);
  };

  const renderSampleList = props.sampleList.map((sample) => (
    <div key={sample} className='sample-text'>
      → {sample}
    </div>
  ));

  return (
    <Styled styles={styles}>
      <div className='app'>
        <div className='top'>
          <div className='header-image' />
        </div>
        <div className='bottom'>
          <div className='header-title'>{props.componentTitle}</div>
          <div>{renderSampleList}</div>
          <button className='button' onClick={handleClick}>
            Let's go!
          </button>
        </div>
      </div>
    </Styled>
  );
};

App.propTypes = {
  sampleList: PropTypes.array,
  componentTitle: PropTypes.string,
};

export default App;
```

**Package Manager:**  
To install Direflow, I used npm;

**Error:**

```
Uncaught Invariant Violation: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.
    in App
    in v (created by ForwardRef)
    in span (created by ForwardRef)
    in ForwardRef
    at http://localhost:3001/direflowBundle.js:28362:32
    at throwOnInvalidObjectType (http://localhost:3001/direflowBundle.js:28365:11)
    at reconcileChildFibers (http://localhost:3001/direflowBundle.js:29215:11)
    at reconcileChildren (http://localhost:3001/direflowBundle.js:31554:32)
    at mountIndeterminateComponent (http://localhost:3001/direflowBundle.js:32298:9)
    at beginWork$1 (http://localhost:3001/direflowBundle.js:33573:20)
    at HTMLUnknownElement.callCallback (http://localhost:3001/direflowBundle.js:13875:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3001/direflowBundle.js:13924:20)
    at invokeGuardedCallback (http://localhost:3001/direflowBundle.js:13977:35)
    at beginWork$$1 (http://localhost:3001/direflowBundle.js:39223:11)
    at performUnitOfWork (http://localhost:3001/direflowBundle.js:38128:16)
    at workLoopSync (http://localhost:3001/direflowBundle.js:38104:26)
    at performSyncWorkOnRoot (http://localhost:3001/direflowBundle.js:37665:15)
    at http://localhost:3001/direflowBundle.js:25825:28
    at unstable_runWithPriority (http://localhost:3001/direflowBundle.js:47567:16)
    at runWithPriority$2 (http://localhost:3001/direflowBundle.js:25771:14)
    at flushSyncCallbackQueueImpl (http://localhost:3001/direflowBundle.js:25820:11)
    at flushSyncCallbackQueue (http://localhost:3001/direflowBundle.js:25808:7)
    at flushPassiveEffectsImpl (http://localhost:3001/direflowBundle.js:38857:7)
    at unstable_runWithPriority (http://localhost:3001/direflowBundle.js:47567:16)
    at runWithPriority$2 (http://localhost:3001/direflowBundle.js:25771:14)
    at flushPassiveEffects (http://localhost:3001/direflowBundle.js:38795:16)
    at http://localhost:3001/direflowBundle.js:38674:15
    at workLoop (http://localhost:3001/direflowBundle.js:47511:38)
    at flushWork (http://localhost:3001/direflowBundle.js:47466:20)
    at MessagePort.performWorkUntilDeadline (http://localhost:3001/direflowBundle.js:46961:33)
(anonymous) @ react-dom.development.js:14850
throwOnInvalidObjectType @ react-dom.development.js:14853
reconcileChildFibers @ react-dom.development.js:15703
reconcileChildren @ react-dom.development.js:18042
mountIndeterminateComponent @ react-dom.development.js:18786
beginWork$1 @ react-dom.development.js:20061
callCallback @ react-dom.development.js:363
invokeGuardedCallbackDev @ react-dom.development.js:412
invokeGuardedCallback @ react-dom.development.js:465
beginWork$$1 @ react-dom.development.js:25711
performUnitOfWork @ react-dom.development.js:24616
workLoopSync @ react-dom.development.js:24592
performSyncWorkOnRoot @ react-dom.development.js:24153
(anonymous) @ react-dom.development.js:12313
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12259
flushSyncCallbackQueueImpl @ react-dom.development.js:12308
flushSyncCallbackQueue @ react-dom.development.js:12296
flushPassiveEffectsImpl @ react-dom.development.js:25345
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12259
flushPassiveEffects @ react-dom.development.js:25283
(anonymous) @ react-dom.development.js:25162
workLoop @ scheduler.development.js:762
flushWork @ scheduler.development.js:717
performWorkUntilDeadline @ scheduler.development.js:212
index.js:1406 The above error occurred in the <App> component:
    in App
    in v (created by ForwardRef)
    in span (created by ForwardRef)
    in ForwardRef

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1406
logCapturedError @ react-dom.development.js:21679
logError @ react-dom.development.js:21715
update.callback @ react-dom.development.js:23075
callCallback @ react-dom.development.js:13936
commitUpdateEffects @ react-dom.development.js:13976
commitUpdateQueue @ react-dom.development.js:13966
commitLifeCycles @ react-dom.development.js:21990
commitLayoutEffects @ react-dom.development.js:25266
callCallback @ react-dom.development.js:363
invokeGuardedCallbackDev @ react-dom.development.js:412
invokeGuardedCallback @ react-dom.development.js:465
commitRootImpl @ react-dom.development.js:25002
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12259
commitRoot @ react-dom.development.js:24843
finishSyncRender @ react-dom.development.js:24220
performSyncWorkOnRoot @ react-dom.development.js:24194
(anonymous) @ react-dom.development.js:12313
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12259
flushSyncCallbackQueueImpl @ react-dom.development.js:12308
flushSyncCallbackQueue @ react-dom.development.js:12296
flushPassiveEffectsImpl @ react-dom.development.js:25345
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12259
flushPassiveEffects @ react-dom.development.js:25283
(anonymous) @ react-dom.development.js:25162
workLoop @ scheduler.development.js:762
flushWork @ scheduler.development.js:717
performWorkUntilDeadline @ scheduler.development.js:212
react-dom.development.js:14850 Uncaught Invariant Violation: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.
    in App
    in v (created by ForwardRef)
    in span (created by ForwardRef)
    in ForwardRef
    at http://localhost:3001/direflowBundle.js:28362:32
    at throwOnInvalidObjectType (http://localhost:3001/direflowBundle.js:28365:11)
    at reconcileChildFibers (http://localhost:3001/direflowBundle.js:29215:11)
    at reconcileChildren (http://localhost:3001/direflowBundle.js:31554:32)
    at mountIndeterminateComponent (http://localhost:3001/direflowBundle.js:32298:9)
    at beginWork$1 (http://localhost:3001/direflowBundle.js:33573:20)
    at HTMLUnknownElement.callCallback (http://localhost:3001/direflowBundle.js:13875:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3001/direflowBundle.js:13924:20)
    at invokeGuardedCallback (http://localhost:3001/direflowBundle.js:13977:35)
    at beginWork$$1 (http://localhost:3001/direflowBundle.js:39223:11)
    at performUnitOfWork (http://localhost:3001/direflowBundle.js:38128:16)
    at workLoopSync (http://localhost:3001/direflowBundle.js:38104:26)
    at performSyncWorkOnRoot (http://localhost:3001/direflowBundle.js:37665:15)
    at http://localhost:3001/direflowBundle.js:25825:28
    at unstable_runWithPriority (http://localhost:3001/direflowBundle.js:47567:16)
    at runWithPriority$2 (http://localhost:3001/direflowBundle.js:25771:14)
    at flushSyncCallbackQueueImpl (http://localhost:3001/direflowBundle.js:25820:11)
    at flushSyncCallbackQueue (http://localhost:3001/direflowBundle.js:25808:7)
    at flushPassiveEffectsImpl (http://localhost:3001/direflowBundle.js:38857:7)
    at unstable_runWithPriority (http://localhost:3001/direflowBundle.js:47567:16)
    at runWithPriority$2 (http://localhost:3001/direflowBundle.js:25771:14)
    at flushPassiveEffects (http://localhost:3001/direflowBundle.js:38795:16)
    at http://localhost:3001/direflowBundle.js:38674:15
    at workLoop (http://localhost:3001/direflowBundle.js:47511:38)
    at flushWork (http://localhost:3001/direflowBundle.js:47466:20)
    at MessagePort.performWorkUntilDeadline (http://localhost:3001/direflowBundle.js:46961:33)
```

**Comment by lucasinocente** [comment]
Hm, my bad. It's not a Direflow bug. Sorry.
